# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81b7b3349d8077ed3acff151daf5ef234322c8c7e8f776e4224ae5eb87e4ea2ce7e01be8dceaa74b9277ae761bde6e5c7355a8690e0aad5976d42eca2be6fde0

test:
  secret_key_base: b8b1f051ea31a970bad16e3f049cf734dc6133e2c86d5225d8b206a078aa4a5eeebd8b01887a6ac521702584044ff0e2eece13b233d7bbb6ae3f19b3380b1a91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
