# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a692a248fd88d1010bb3b6576c7b863c74c669f97f3b6cc35d536824fa9844156c394f29d244bcf9bd2104dd6d2e824d3f91f7691f6569ed1a0b12b0153f755

test:
  secret_key_base: f0886a194145e1cca94ad9ed8fa88061652726d3274c6d73b14fc01e677bbd35e94cedae1b0ed4a97ff912859de4e4edb86a4266b04f542020a75667485f9878

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
