# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 519abc611ef52791f9ae44c580bb1a692af10691706ed53b424ebde38223db2d243618c55795027c2ff6599ba56c44f468b9cdddf5bf71121ed38ffdbc172c6c

test:
  secret_key_base: f810cd78cdd4004181044a1c410ddba31a9cb79e6f057f33699bd1a116906def6677c93121e99c31faefe3aabe8d4bab6bf3abdbfdea83fab99b0a456634584a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
